pipeline {
    agent any

    stages{
        stage('Server Details'){
            steps{
                echo "This will print my server details"
            }
        }

         stage('Details of Server'){
            steps{
                sh 'uname -a'
            }
        }

        stage('Date of Server'){
            steps{
                sh 'date'
            }
        }

        stage('Disk Usage'){
            steps{
                sh 'df -h'
            }
        }

        stage('Memory Usage'){
            steps{
                sh 'free -h'
            }
        }

        stage('Cpu Details'){
            steps{
                sh 'lscpu'
            }
        }
    }

}